spring:
  datasource:
    hikari:
      username: boardAdmin
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      password: test1234!@#$
  jpa:
    generate-ddl: 'false'
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'
